# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'range_disp.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(846, 289)
        MainWindow.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(40, 60, 221, 91))
        self.lcdNumber.setStyleSheet("color: rgb(0, 171, 50);")
        self.lcdNumber.setObjectName("lcdNumber")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 20, 241, 141))
        self.groupBox.setStyleSheet("color: rgb(255, 243, 0);\n"
"border-color: rgb(255, 255, 255);")
        self.groupBox.setObjectName("groupBox")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(300, 20, 241, 141))
        self.groupBox_2.setStyleSheet("color: rgb(255, 243, 0);\n"
"border-top-color: rgb(255, 255, 255);")
        self.groupBox_2.setObjectName("groupBox_2")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.groupBox_2)
        self.lcdNumber_2.setGeometry(QtCore.QRect(10, 40, 221, 91))
        self.lcdNumber_2.setStyleSheet("color: rgb(0, 171, 50);")
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(570, 20, 241, 141))
        self.groupBox_3.setStyleSheet("color: rgb(255, 243, 0);")
        self.groupBox_3.setObjectName("groupBox_3")
        self.lcdNumber_3 = QtWidgets.QLCDNumber(self.groupBox_3)
        self.lcdNumber_3.setGeometry(QtCore.QRect(10, 40, 221, 91))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.lcdNumber_3.setFont(font)
        self.lcdNumber_3.setStyleSheet("color: rgb(0, 171, 50);")
        self.lcdNumber_3.setLineWidth(2)
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 190, 221, 41))
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("background-color: rgb(246, 97, 81);")
        self.label.setMidLineWidth(10)
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(310, 190, 221, 41))
        self.label_2.setAutoFillBackground(False)
        self.label_2.setStyleSheet("background-color: rgb(246, 97, 81);")
        self.label_2.setMidLineWidth(10)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(580, 190, 221, 41))
        self.label_3.setAutoFillBackground(False)
        self.label_3.setStyleSheet("background-color: rgb(246, 97, 81);")
        self.label_3.setMidLineWidth(10)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(30, 160, 241, 81))
        self.groupBox_4.setStyleSheet("color: rgb(255, 243, 0);")
        self.groupBox_4.setObjectName("groupBox_4")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(300, 160, 241, 81))
        self.groupBox_5.setStyleSheet("color: rgb(255, 243, 0);")
        self.groupBox_5.setObjectName("groupBox_5")
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(570, 160, 241, 81))
        self.groupBox_6.setStyleSheet("color: rgb(255, 243, 0);")
        self.groupBox_6.setObjectName("groupBox_6")
        self.groupBox_6.raise_()
        self.groupBox_5.raise_()
        self.groupBox_4.raise_()
        self.groupBox.raise_()
        self.lcdNumber.raise_()
        self.groupBox_2.raise_()
        self.groupBox_3.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 846, 22))
        self.menubar.setObjectName("menubar")
        self.menuUWB_ranging = QtWidgets.QMenu(self.menubar)
        self.menuUWB_ranging.setObjectName("menuUWB_ranging")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuUWB_ranging.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Anchor-tag Display"))
        self.groupBox.setTitle(_translate("MainWindow", "Anchor #1"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Anchor #2"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Anchor #3"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Status"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Status"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Status"))
        self.menuUWB_ranging.setTitle(_translate("MainWindow", "UWB ranging [mm]"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
